services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # Cloudflared espera TUNNEL_TOKEN, mapeamos desde CLOUDFLARE_TUNNEL_TOKEN
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      # Montar el archivo de configuración
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    command: tunnel --no-autoupdate --edge-ip-version auto --config /etc/cloudflared/config.yml run
    networks:
      - entry
    # Nota: Traefik debe estar corriendo en la misma red 'entry' para que cloudflared pueda conectarse

networks:
  entry:
    name: entry
    external: true

