version: '3.8'

services:
  error-page:
    image: nginx:alpine
    container_name: error-page
    restart: unless-stopped
    command: >
      sh -c "
      echo '<!DOCTYPE html>
      <html>
      <head>
          <meta charset=\"UTF-8\">
          <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
          <title>Tekkisma</title>
          <style>
              * { margin: 0; padding: 0; box-sizing: border-box; }
              html, body { height: 100%; }
              body {
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;
                  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  color: white;
              }
              .container {
                  text-align: center;
                  padding: 2rem;
              }
              h1 {
                  font-size: 4rem;
                  font-weight: 300;
                  letter-spacing: 0.1em;
                  text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
                  margin-bottom: 1rem;
              }
              p {
                  font-size: 1.2rem;
                  opacity: 0.9;
                  text-shadow: 1px 1px 2px rgba(0,0,0,0.2);
              }
          </style>
      </head>
      <body>
          <div class=\"container\">
              <h1>Tekkisma</h1>
              <p>Servicio no disponible</p>
          </div>
      </body>
      </html>' > /usr/share/nginx/html/index.html &&
      nginx -g 'daemon off;'
      "
    networks:
      - entry

networks:
  entry:
    name: entry
    external: true

