# MinIO - Almacenamiento S3 self-hosted

services:
  minio:
    image: minio/minio:latest
    container_name: storage-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # Configuración opcional
      MINIO_BROWSER: ${MINIO_BROWSER:-on}
      MINIO_DOMAIN: ${MINIO_DOMAIN:-}
    volumes:
      - ../data/storage/minio:/data
    networks:
      - storage
      - entry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"

networks:
  storage:
    name: storage
    external: true
  entry:
    name: entry
    external: true
