version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    container_name: storage-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-shared}
    volumes:
      - ../data/storage/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  storage:
    name: storage
    driver: bridge
    external: false

