version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: storage-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ../data/storage/redis:/data
    env_file:
      - ./.env
    networks:
      - storage
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  storage:
    name: storage
    driver: bridge
    external: false

